# Physics 231: Final Project
## Adiabatic Evolution of the Anharmonic Oscillator

In [1]:
import numpy as np

### Defining the Ladder Operators in the Harmonic Oscillator Basis

In [2]:
def op_a(n):
    mat = np.zeros((n, n))
    for i in range(n-1):
        mat[i][i+1] = np.sqrt(i+1)
    return mat

def op_adag(n):
    mat = np.zeros((n, n))
    for i in range(n-1):
        mat[i+1][i] = np.sqrt(i+1)
    return mat

def op_n(n):
    a = op_a(n)
    adag = op_adag(n)
    mat = np.dot(adag,a)
    return mat

In [3]:
a = op_a(5)
b = op_adag(5)
print(np.dot(a,b)-np.dot(b,a)) #expect [a,adag] = 1
print(op_n(5))

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. -4.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 4.]]


__Note:__ The error in the last row is a result of the fact that the originally infinite Hilbert Space has been truncated.

### Defining the x,p in terms of Dagger Operators

$$x = \sqrt{\frac{\hbar}{2m\omega}}(a+a^+)$$

$$p = -i\sqrt{\frac{m\omega\hbar}{2}}(a-a^+)$$

#### We will be setting $\hbar = m = \omega = 1$

In [4]:
def op_x(n):
    mat = np.sqrt(1/2)*(op_a(n) + op_adag(n))
    return mat

def op_p(n):
    mat = (-1j)*np.sqrt(1/2)*(op_a(n) - op_adag(n))
    return mat

In [5]:
x = op_x(5)
p = op_p(5)
print(np.imag(np.dot(x,p)-np.dot(p,x))) # expect [x,p] = ihbar

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. -4.]]


#### Test: Is $x^2$ the same from definition of x and dagger operators

In [6]:
# FROM DAGGER OPERATORS
a = op_a(5)
adag = op_adag(5)
# x2 = 0.5*((np.dot(a,a)+np.dot(adag,adag)+np.eye(5)+2*op_n(5))) # using aa^+ = 1 + n
x2 = 0.5*((np.dot(a,a)+np.dot(adag,adag)+np.dot(adag,a)+np.dot(a,adag)))
x2

array([[0.5       , 0.        , 0.70710678, 0.        , 0.        ],
       [0.        , 1.5       , 0.        , 1.22474487, 0.        ],
       [0.70710678, 0.        , 2.5       , 0.        , 1.73205081],
       [0.        , 1.22474487, 0.        , 3.5       , 0.        ],
       [0.        , 0.        , 1.73205081, 0.        , 2.        ]])

In [7]:
# FROM DEFINITION OF x
x = op_x(5)
x2_test = np.dot(x,x)
x2_test

array([[0.5       , 0.        , 0.70710678, 0.        , 0.        ],
       [0.        , 1.5       , 0.        , 1.22474487, 0.        ],
       [0.70710678, 0.        , 2.5       , 0.        , 1.73205081],
       [0.        , 1.22474487, 0.        , 3.5       , 0.        ],
       [0.        , 0.        , 1.73205081, 0.        , 2.        ]])

__Result:__ Both are same, as expected. So our life is good.

In [8]:
def op_x2(n):
    x = op_x(n)
    mat = np.dot(x,x)
    return mat

def op_p2(n):
    p = op_p(n)
    mat = np.dot(p,p)
    return mat

def op_x3(n):
    x = op_x(n)
    x2 = op_x2(n)
    mat = np.dot(x,x2)
    return mat

def op_x4(n):
    x2 = op_x2(n)
    mat = np.dot(x2,x2)
    return mat

### Defining the Hamiltonians in terms of Dagger Operators

$$H_0 = \frac{p^2}{2} + \frac{x^2}{2}$$

$$H_f = \frac{p^2}{2} + \frac{(x-b)^2}{2} + \lambda(x-b)^4 $$

In [9]:
def op_Hi(n):
    x2 = op_x2(n)
    p2 = op_p2(n)
    mat = 0.5*(x2 + p2) 
    return mat
    
def op_Hf(n, b = 0, lam): # complete the  definition
    x2 = op_x2(n)
    p2 = op_p2(n)
    mat = 0.5*(x2 + p2) 
    

SyntaxError: non-default argument follows default argument (<ipython-input-9-a5d01c939875>, line 7)

#### Sanity Checks

In [63]:
x = op_x(5) # element wise subtraction
vec = np.asarray([1,0,0,0,0])
np.dot(vec,np.dot(x,vec))

0.0

In [57]:
x = op_x(5) # element wise subtraction
vec = np.asarray([0,0.6,0.8,0,0])
np.dot(vec,np.dot(x,vec))

0.9600000000000002

In [62]:
x = op_x(5) 
vec1 = np.asarray([0,1,0,0,0])
vec2 = np.asarray([0,0,1,0,0])
(0.6)*(0.8)*(np.dot(vec1,np.dot(x,vec2)) + np.dot(vec2,np.dot(x,vec1)))

0.9600000000000002

In [50]:
x = op_x(5) - 3*np.eye(5) # subtracting 3*I
vec = np.asarray([1,0,0,0,0])
np.dot(vec,np.dot(x,vec))

-3.0

In [40]:
x = op_x(5) - 3*np.eye(5) # subtracting 3*I
vec = np.asarray([0,0.6,0.8,0,0])
np.dot(vec,np.dot(x,vec))

-2.04

In [46]:
x = op_x(5) - 3 # element wise subtraction
vec = np.asarray([0,0.6,0.8,0,0])
np.dot(vec,np.dot(x,vec))

-4.92